$(document).ready(function(){
    $(".design-clickable").click(function(){
        $(".design-showing").toggle();
        $(".design-hidden").toggle();
    });
});
$(document).ready(function(){
    $(".development-clickable").click(function(){
        $(".development-showing").toggle();
        $(".development-hidden").toggle();
    });
});
$(document).ready(function(){
    $(".product-clickable").click(function(){
        $(".prodManagement-showing").toggle();
        $(".prodManagement-hidden").toggle();
    });
});
$(document).ready(function(){
    $(".border").hide();
    $("img").animate({
        opacity:5
    });
    $("img").hover(function(){
        $(this).stop().animate({
            opacity:0.4},200);
            $(".border").fadeIn();
        }
        ,function(){
            $(this).stop().animate({
                opacity:1},500);
                $(".border").fadeOut();  
        });
    });
